routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/questions', 'QuestionController')->except('show');
Route::resource('/questions.answers', 'AnswerController')->except(['index','show','create']);

Route::get('/questions/{slug}', 'QuestionController@show')->name('questions.show');

Route::post('/answers/{answer}/accept', 'AcceptAnswerController@accept')->name('accept.answers');
Route::post('/questions/{question}/favourites', 'FavouritesController@store')->name('questions.favourite');
Route::delete('/questions/{question}/favourites', 'FavouritesController@destroy')->name('questions.unfavourite');
Route::post('/questions/{question}/vote', 'VoteQuestionController@vote')->name('questions.vote');
Route::post('/answers/{answer}/vote', 'VoteAnswerController@vote')->name('answers.vote');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Null_;

class Answer extends Model
{
    protected $fillable=[ 'body', 'user_id'];

    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }
    public static function boot()
    {
        parent::boot();
        static::created(function($answer){
            $answer->question->increment('answers_count');
        });
        static::deleted(function($answer){
            $question = $answer->question;
            $answer->question->decrement('answers_count');
            if ($question->best_answer_id===$answer->id){
                $question->best_answer_id= Null ;
                    $question->save();
            }
        });
    }
    public function getStatusAttribute(){
        return $this->id === $this->question->best_answers_id ? 'vote-accept': '';
    }
    public function getIsBestAttribute(){
        return $this->id === $this->question->best_answers_id ;
    }

    public function getCreateDateAttribute(){
        return $this->created_at->diffForHumans();
    }
    public function votes(){
        return $this->morphToMany(User::class, 'votable')->withTimestamps();
    }
    public function upVotes(){
        return $this->votes()->wherePivot('vote',1);
    }
    public function downVotes(){
        return $this->votes()->wherePivot('vote',-1);
    }

}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AnswerController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question,Request $request)
    {
        $question->answers()->create($request->validate([
            'body'=>'required'
        ])+['user_id'=>Auth::id()]);
        return back()->with('success', 'Your answer submitted successfully');
    }


    public function edit(Question $question,Answer $answer)
    {
        $this->authorize('update', $answer);
        return view('answers.edit',compact('question','answer'));
    }


    public function update(Request $request, Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);
        $answer->update($request->validate([
            'body'=>'required'
        ]));
        return redirect()->route('questions.show' , $question->slug)->with('success','Answer Updated Successfully');
    }

    public function destroy(Question $question,Answer $answer)
    {
        $this->authorize('delete', $answer);
        $answer->delete();
        return back()->with('success', 'Your Answer delete successfully');
    }
}

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-text-center">
                            <h3 >Edit Answers</h3>
                            {{--                            <h3 class="ml-auto">--}}
                            {{--                                <a class="btn btn-sm btn-outline-dark" style="border-radius: 12px;" href="{{route('questions.index')}}">Question List</a>--}}
                            {{--                            </h3>--}}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            {!!   Form::open([
                            'route'=>['questions.answers.update', $question->id, $answer->id],
                            'method'=>'put',
                            ])   !!}
                            <div class="form-group row">
                                <div class="col-sm-10">
                                    {!! Form::textarea('body',$answer->body,[
                                            'class' => 'form-control',
                                            'id' => 'answer_body',
                                            'placeholder' => 'Enter the Answer Description here...',
                                        ]) !!}
                                    @if ($errors->has('body'))
                                        <span style="color: red">*{{ $errors->first('body') }}</span>
                                    @endif
                                </div>
                            </div>
                            {!! Form::button('Answer-Update', [
                                            'class' => 'btn btn-sm btn-primary',
                                            'style'=> 'border-radius: 13px;',
                                            'type' => 'submit',
                                        ]) !!}
                            {!!   Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection