routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/questions', 'QuestionController')->except('show');
Route::resource('/questions.answers', 'AnswerController')->except(['index','show','create']);

Route::get('/questions/{slug}', 'QuestionController@show')->name('questions.show');

Route::post('/answers/{answer}/accept', 'AcceptAnswerController@accept')->name('accept.answers');
Route::post('/questions/{question}/favourites', 'FavouritesController@store')->name('questions.favourite');
Route::delete('/questions/{question}/favourites', 'FavouritesController@destroy')->name('questions.unfavourite');
Route::post('/questions/{question}/vote', 'VoteQuestionController@vote')->name('questions.vote');
Route::post('/answers/{answer}/vote', 'VoteAnswerController@vote')->name('answers.vote');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Null_;

class Answer extends Model
{
    protected $fillable=[ 'body', 'user_id'];

    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }
    public static function boot()
    {
        parent::boot();
        static::created(function($answer){
            $answer->question->increment('answers_count');
        });
        static::deleted(function($answer){
            $question = $answer->question;
            $answer->question->decrement('answers_count');
            if ($question->best_answer_id===$answer->id){
                $question->best_answer_id= Null ;
                    $question->save();
            }
        });
    }
    public function getStatusAttribute(){
        return $this->id === $this->question->best_answers_id ? 'vote-accept': '';
    }
    public function getIsBestAttribute(){
        return $this->id === $this->question->best_answers_id ;
    }

    public function getCreateDateAttribute(){
        return $this->created_at->diffForHumans();
    }
    public function votes(){
        return $this->morphToMany(User::class, 'votable')->withTimestamps();
    }
    public function upVotes(){
        return $this->votes()->wherePivot('vote',1);
    }
    public function downVotes(){
        return $this->votes()->wherePivot('vote',-1);
    }

}

app/Question.php
<?php

namespace App;
use App\Answer;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable=['title', 'body'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function setTitleAttribute($value)
    {
         $this->attributes['title'] = $value;
         $this->attributes['slug'] = str_slug($value);
    }
    public function getUrlAttribute()
    {
        return route('questions.show', $this->slug);
    }
    public function getBodyHtmlAttribute()
    {
        return clean(\Parsedown::instance()->text($this->body));
    }

    public function getCreateDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getStatusAttribute()
    {
        if($this->answers_count > 0){
            if ($this->best_answers_id){
                return "answered-accepted";
            }
            return "answered";
        }
        return "unanswered";
    }
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function bestAcceptAnswer(Answer $answer){
        $this->best_answers_id = $answer->id;
        $this->save();
    }
    public function favourites()
    {
        return $this->belongsToMany(User::class, 'favourites')
            ->withTimestamps();
    }
    public function isFavourited(){
        return $this->favourites()
                ->where('user_id', auth()->id())
                ->count() > 0;
    }
    public function getIsFavouritedAttribute(){
        return $this->isFavourited();
    }
    public function getFavouritesCountAttribute(){
        return $this->favourites()->count() ;
    }
    public function votes(){
        return $this->morphToMany(User::class, 'votable')->withTimestamps();
    }
    public function upVotes(){
        return $this->votes()->wherePivot('vote',1);
    }
    public function downVotes(){
            return $this->votes()->wherePivot('vote',-1);
    }


}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AskQuestionRequest;
use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth',['except'=>['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::latest()->paginate(6);
        return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question = new Question();
        return view('questions.create', compact('question'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
        $request->user()->questions()
                ->create($request->only('title','body'));
        return redirect()->route('questions.index')
                ->with('success', 'Your question create successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $this->authorize('update', $question);
        return view('questions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        $this->authorize('update', $question);
        $question->update($request->only('title','body'));
        return redirect()->route('questions.index')
            ->with('success', 'Your question update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $this->authorize('delete', $question);
        $question->delete();
        return redirect()->route('questions.index')
            ->with('success', 'Your question delete successfully');
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-text-center">
                            <h3 >Create Questions</h3>
                            <h3 class="ml-auto">
                                <a class="btn btn-sm btn-outline-dark" style="border-radius: 12px;" href="{{route('questions.index')}}">Question List</a>
                            </h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                        {!!   Form::open([
                        'route'=>'questions.store',
                        'method'=>'post',
                        ])   !!}
                            <div class="form-group row">
                                {!! Form::label('Question-Title :-', null, ['class' => 'col-sm-3 col-form-label']) !!}
                                <div class="col-sm-10">
                            {!! Form::text( 'title', null, [
                                'class'=>'form-control',
                                'id'=>'question_title',
                                'placeholder' => 'Enter the Questions Title here...',

                                    ]) !!}
                                    @if ($errors->has('title'))
                                        <span style="color: red">*{{ $errors->first('title') }}</span>
                                    @endif

                                </div>
                            </div>
                            <div class="form-group row">
                                {!! Form::label('Question-Body:-', null, ['class' => 'col-sm-3 col-form-label']) !!}

                                <div class="col-sm-10">
                                    {!! Form::textarea('body', null, [
                                            'class' => 'form-control',
                                            'id' => 'question_body',
                                            'placeholder' => 'Enter the Questions Description here...',

                                        ]) !!}
                                    @if ($errors->has('body'))
                                        <span style="color: red">*{{ $errors->first('body') }}</span>
                                    @endif

                                </div>
                            </div>
                            {!! Form::button('Question-Submit', [
                                            'class' => 'btn btn-sm btn-primary',
                                            'style'=> 'border-radius: 13px;',
                                            'type' => 'submit',
                                        ]) !!}

                            {!!   Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-text-center">
                            <h3 >All Questions</h3>
                            <h3 class="ml-auto">
                                <a class="btn btn-sm btn-outline-dark" style="border-radius: 12px;" href="{{route('questions.create')}}">Ask me</a>
                            </h3>
                        </div>
                    </div>
                    @include('layouts._message')
                    @foreach($questions as $question)
                        <div class="card-body">
                            <div class="media">
                                <div class="d-flex flex-column counters">
                                    <div class="vote">
                                        <strong style="display: block; font-size: 2em;"> {{$question->votes_count}}</strong>
                                        {{str_plural('vote', $question->votes_count)}}
                                    </div>
                                    <div class="status {{$question->status}}">
                                        <strong style="display: block; font-size: 2em;">{{$question->answers_count}}</strong>
                                        {{str_plural('answer', $question->answers_count)}}
                                    </div>
                                    <div class="views" style="margin-top: 10px;">
                                      {{$question->views}}
                                        {{str_plural('view', $question->views)}}
                                    </div>
                                </div>
                                <div class="media-body">
                                    <div class="d-flex align-items-center">
                                        <h3 class="mt-3">
                                            <a href="{{$question->url}}">
                                                {{$question->title }}
                                            </a>
                                        </h3>
                                        <div class="ml-auto">
                                            @can('update', $question)
                                            <a class="btn btn-sm btn-outline-success" style="border-radius:10px" href="{{route('questions.edit', $question->id)}}">Edit</a>
                                            @endcan
                                            @can('delete', $question)
                                                {!! Form::open([
                                                'route'=>['questions.destroy', $question->id],
                                                'method'=> 'delete',
                                                'style'=> 'display:inline'
                                            ]) !!}
                                            {!! Form::button('Delete', [
                                                'type'=> 'submit',
                                                'class'=>'btn btn-outline-danger btn-sm',
                                                'style'=>'border-radius:12px',
                                                'onclick'=> 'return confirm("Are You Sure , Want To Delete It Permanently?" )',
                                            ]) !!}
                                            {!! Form::close() !!}
                                                @endcan
                                        </div>
                                    </div>
                                    <p class="lead">
                                        Asked By:-
                                        <a href="#">
                                            {{$question->user->name}}
                                        </a>
                                        <small class="text-muted">
                                            {{$question->create_date}}
                                        </small>
                                    </p>
                                    {{str_limit($question->body, 250)}}
                                </div>
                            </div>
                        </div>
                        <hr>
                    @endforeach
                    <ul class="pagination justify-content-center mb-4">
                        <li class="page-item">
                            {{$questions->links()}}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-text-center">
                            <h3 >{{$question->title}}</h3>
                            <h3 class="ml-auto">
                                <a class="btn btn-sm btn-outline-dark" style="border-radius: 12px;" href="{{route('questions.index')}}">Question List</a>
                            </h3>
                        </div>
                    </div>
                    <div class="media">
                        <div class="d-flex flex-column votes-control ">
                            <a class="vote-down  mt-3 {{Auth::guest() ? 'off':''}}"
                               onclick="event.preventDefault(); document.getElementById('questions-vote-down-{{$question->id}}').submit()" >
                                <i class="fas fa-thumbs-down fa-2x"></i>
                            </a>
                            <form action="/questions/{{$question->id}}/vote" id="questions-vote-down-{{$question->id}}" method="post" style="display: none; ">
                                @csrf
                                <input type="hidden" name="vote" value="-1">
                            </form>
                            <span>
                                {{$question->votes_count}}
                            </span>
                            <a class="vote-up {{Auth::guest() ? 'off':''}}"
                                   onclick="event.preventDefault(); document.getElementById('questions-vote-up-{{$question->id}}').submit()" >
                                <i class="fas fa-thumbs-up fa-2x"></i>
                            </a>
                            <form action="/questions/{{$question->id}}/vote" id="questions-vote-up-{{$question->id}}" method="post" style="display: none; ">
                                @csrf
                                <input type="hidden" name="vote" value="1">
                            </form>



                            <a class="favourite fabs mt-2 {{Auth::guest() ? 'off':($question->is_favourited) ? 'fabs':''}}"
                               onclick="event.preventDefault(); document.getElementById('questions-favourites-{{$question->id}}').submit()">
                                <i class="fas fa-star fa-1x"></i>
                            </a>
                            <span>{{$question->favourites_count}}</span>
                            <form action="/questions/{{$question->id}}/favourites" id="questions-favourites-{{$question->id}}" method="post" style="display: none; ">
                                @csrf
                                @if($question->is_favourited)
                                    @method('delete')
                                @endif
                            </form>
                        </div>
                        <div class="media-body">
                   {!!  $question->body_html!!}
                        <div class="float-right">
                                            <span class="text-muted">
                                                Questioned {!! $question->create_date !!}
                                            </span>
                            <div class="media">
                                <a class="pr-2" href="{!! $question->user->url !!}">
                                    <img src="{!! $question->user->avatar !!}" alt="avatar">
                                </a>
                                <div class="media-body">
                                    <a href="{!! $question->user->url !!}">
                                        {!! $question->user->name !!}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{{--      >>>>>>>>>>>>>>>>>>  This is the Answer Section<<<<<<<<<<<<<<<<<--}}

        <div class="row mt-5">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            @include('layouts._message')
                            <h2>Your Answer</h2>
                            {!!   Form::open([
                            'route'=>['questions.answers.store', $question->id],
                            'method'=>'post',
                            ])   !!}
                            <div class="form-group">
                                {!! Form::textarea('body', null, [
                                        'class' => 'form-control',
                                        'placeholder' => 'Enter Your Answer Description here...',
                                    ]) !!}
                                @if ($errors->has('body'))
                                    <span style="color: red">*{{ $errors->first('body') }}</span>
                                @endif

                            </div>
                            {!! Form::button('Submit-Answer', [
                                            'class' => 'btn btn-sm btn-primary',
                                            'style'=> 'border-radius: 13px;',
                                            'type' => 'submit',
                                        ]) !!}
                            {!!   Form::close() !!}
                            <hr>
                            <h4>
                                {!! $question->answers_count !!}
                                {!! str_plural('- Answer' , $question->answers_count) !!}
                            </h4>
                            <hr>
                            @foreach($question->answers as $answer)
                                <div class="media">
                                    <div class="d-flex flex-column votes-control ">
                                        <a class="vote-down  mt-3 {{Auth::guest() ? 'off':''}}"
                                           onclick="event.preventDefault(); document.getElementById('answers-vote-down-{{$answer->id}}').submit()" >
                                            <i class="fas fa-thumbs-down fa-2x"></i>
                                        </a>
                                        <form action="/answers/{{$answer->id}}/vote" id="answers-vote-down-{{$answer->id}}" method="post" style="display: none; ">
                                            @csrf
                                            <input type="hidden" name="vote" value="-1">
                                        </form>
                                        <span>
                                            {{$answer->votes_count}}
                                        </span>
                                        <a class="vote-up {{Auth::guest() ? 'off':''}}"
                                           onclick="event.preventDefault(); document.getElementById('answers-vote-up-{{$answer->id}}').submit()" >
                                            <i class="fas fa-thumbs-up fa-2x"></i>
                                        </a>
                                        <form action="/answers/{{$answer->id}}/vote" id="answers-vote-up-{{$answer->id}}" method="post" style="display: none; ">
                                            @csrf
                                            <input type="hidden" name="vote" value="1">
                                        </form>
                                        <a class="favourite fabs mt-2 {{Auth::guest() ? 'off':($question->is_favourited) ? 'fabs':''}}"
                                           onclick="event.preventDefault(); document.getElementById('questions-favourites-{{$question->id}}').submit()">
                                            <i class="fas fa-star fa-1x"></i>
                                        </a>
                                        <span>{{$question->favourites_count}}</span>
                                        <form action="/questions/{{$question->id}}/favourites" id="questions-favourites-{{$question->id}}" method="post" style="display: none; ">
                                            @csrf
                                            @if($question->is_favourited)
                                                @method('delete')
                                            @endif
                                        </form>
                                        @can('accept', $answer)
                                        <a class="favourite mt-4 {{$answer->status}}" onclick="event.preventDefault(); document.getElementById('accept-answer-{{$answer->id}}').submit()" >
                                            <i class="fas fa-check fa-2x"></i>
                                        </a>
                                            <form action="{{route('accept.answers', $answer->id)}}" method="post" style="display:none;" id="accept-answer-{{$answer->id}}">
                                                @csrf
                                            </form>
                                            @else
                                                @if($answer->is_best)
                                                    <a class="favourite mt-4 {{$answer->status}}" >
                                                        <i class="fas fa-check fa-2x"></i>
                                                    </a>
                                                @endif
                                        @endcan
                                    </div>
                                    <div class="media-body">
                                        {!! $answer->body_html !!}
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="ml-auto">
                                                    @can('update', $answer)
                                                        <a class="btn btn-sm btn-outline-success" style="border-radius:10px" href="{{route('questions.answers.edit', [$question->id, $answer->id])}}">Edit</a>
                                                    @endcan
                                                    @can('delete', $answer)
                                                        {!! Form::open([
                                                        'route'=>['questions.answers.destroy', $question->id,$answer->id],
                                                        'method'=> 'delete',
                                                        'style'=> 'display:inline'
                                                    ]) !!}
                                                        {!! Form::button('Delete', [
                                                            'type'=> 'submit',
                                                            'class'=>'btn btn-outline-danger btn-sm',
                                                            'style'=>'border-radius:12px',
                                                            'onclick'=> 'return confirm("Are You Sure , Want To Delete It Permanently?" )',
                                                        ]) !!}
                                                        {!! Form::close() !!}
                                                    @endcan
                                                </div>
                                            </div>
                                            <div class="col-md-4"></div>
                                            <div class="col-md-4">
                                                <div class="float-right">
                                                    <span class="text-muted">
                                                        Answered {!! $answer->create_date !!}
                                                    </span>
                                                    <div class="media">
                                                        <div class="media-body">
                                                            <a class="pr-2" href="{!! $answer->user->url !!}">
                                                                <img src="{!! $answer->user->avatar !!}" alt="avatar">
                                                            </a>

                                                            <a class="pr-2" href="{!! $answer->user->url !!}">
                                                                {!! $answer->user->name !!}
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection